export const TABLE_HEADERS = [
  { display: "Acronym", fieldName: "acronym" },
  { display: "Full Name", fieldName: "fullName" },
  { display: "Design Org", fieldName: "designOrg" },
  { display: "Coolant", fieldName: "coolant" },
  { display: "Moderator", fieldName: "moderator" },
  { display: "Type", fieldName: "type" },
  { display: "Design Status", fieldName: "designStatus" },
  { display: "Country", fieldName: "country" },
  { display: "Neutron Spectrum", fieldName: "neutronSpectrum" },
  { display: "Reactor Thermal Output", fieldName: "reactorThermalOutput" },
  { display: "Power Plant Gross Output", fieldName: "powerPlantGrossOutput" },
  { display: "Power Plant Net Output", fieldName: "powerPlantNetOutput" },
  { display: "Plant Efficiency Net (%)", fieldName: "plantEfficiencyNet" },
  {
    display: "Non-Electrical Applications",
    fieldName: "nonElectricalApplications",
  },
  { display: "Steam-Flow Rates(kg/s)", fieldName: "steamFlowRate" },
  { display: "Steam Pressure (MPA)", fieldName: "steamPressure" },
  { display: "Steam Temperature (°C)", fieldName: "steamTemperature" },
  { display: "Feedwater Flow Rate (kg/s)", fieldName: "feedwaterFlowRate" },
  { display: "Feedwater Temperature (°C)", fieldName: "feedwaterTemperature" },
  { display: "Thermodynamic Cycle", fieldName: "thermodynamicCycle" },
  { display: "Core Coolant", fieldName: "coreCoolant" },
  { display: "Primary Coolant Flow Rate", fieldName: "primaryCoolantFlowRate" },
  {
    display: "Reactor Operating Pressure (MPA)",
    fieldName: "reactorOperatingPressure",
  },
  {
    display: "Coolant Inlet Temperature (°C)",
    fieldName: "coolantInletTemperature",
  },
  {
    display: "Coolant Outlet Temperature (°C)",
    fieldName: "coolantOutletTemperature",
  },
  { display: "Delta Temperature (°C)", fieldName: "deltaTemperature" },
  { display: "Active Core Height (m)", fieldName: "activeCoreHeight" },
  {
    display: "Equivalent Core Diameter (m)",
    fieldName: "equivalentCoreDiameter",
  },
  {
    display: "Average Linear Heat Rate (kW/m)",
    fieldName: "averageLinearHeatRate",
  },
  {
    display: "Average Fuel Power Density (kW/kgU)",
    fieldName: "averageFuelPowerDensity",
  },
  {
    display: "Average core power density[kW/kgU]",
    fieldName: "averageCorePowerDensity",
  },
  {
    display: "Outer diameter of fuel rods[mm]",
    fieldName: "outerDiameterFuelRods",
  },
  {
    display: "Rod array of a fuel assembly",
    fieldName: "rodArrayOfFuelAssembly",
  },
  { display: "Lattice geometry", fieldName: "latticeGeometry" },
  { display: "Number of fuel assemblies", fieldName: "numberOfFuelAssemblies" },
  { display: "Fuel Material", fieldName: "fuelMaterial" },
  { display: "Cladding material", fieldName: "claddingMaterial" },
  {
    display: "Enrichment of reload fuel[wt %]",
    fieldName: "enrichmentOfReloadFuel",
  },
  { display: "Fuel cycle length[Months]", fieldName: "fuelCycleLength" },
  {
    display: "Average discharge burnup[MWd/kg]",
    fieldName: "averageDischargeBurnup",
  },
  { display: "Burnable absorber", fieldName: "burnableAbsorber" },
  { display: "Control rod absorber", fieldName: "controlRodAbsorber" },
  { display: "Soluble neutron absorber", fieldName: "solubleNeutronAbsorber" },
  {
    display: "Inner diameter of cylindrical shell[mm]",
    fieldName: "innerDiameterOfCylindricalShell",
  },
  {
    display: "Wall thickness of cylindrical shell[mm]",
    fieldName: "wallThicknessOfCylindricalShell",
  },
  { display: "Base material", fieldName: "baseMaterial" },
  { display: "Total height, inside[mm]", fieldName: "totalHeightInside" },
  { display: "Transport weight[tonne]", fieldName: "transportWeight" },
];

export const TABLE_DATA = [
  {
    acronym: "4S",
    fullName: "Super-safe, small and simple",
    designOrg: "Toshiba Energy Systems & Solutions Corp",
    coolant: "-",
    moderator: "-",
    type: "SFR",
    designStatus: "Under Design",
    country: "Japan",
    neutronSpectrum: "-",
    reactorThermalOutput: "30",
    powerPlantGrossOutput: "-",
    powerPlantNetOutput: "1315",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "-",
    steamTemperature: "",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "",
    thermodynamicCycle: "Rankine",
    coreCoolant: "-",
    primaryCoolantFlowRate: "",
    reactorOperatingPressure: "0.2",
    coolantInletTemperature: "355",
    coolantOutletTemperature: "-",
    deltaTemperature: "-",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "-",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "-",
    numberOfFuelAssemblies: "",
    fuelMaterial: "U-10Zr",
    claddingMaterial: "HT-9",
    enrichmentOfReloadFuel: "17",
    fuelCycleLength: "360",
    averageDischargeBurnup: "34",
    burnableAbsorber: "N/A",
    controlRodAbsorber: "-",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "SS304",
    totalHeightInside: "-",
    transportWeight: "-",
  },
  {
    acronym: "ALFRED",
    fullName: "Advanced Lead Fast Reactor European Demonstrator",
    designOrg: "Ansaldo Nucleare",
    coolant: "Lead",
    moderator: "No Moderator",
    type: "LFR",
    designStatus: "Under Design",
    country: "EU",
    neutronSpectrum: "Fast",
    reactorThermalOutput: "300",
    powerPlantGrossOutput: "125",
    powerPlantNetOutput: "125",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "-",
    steamTemperature: "",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "",
    thermodynamicCycle: "-",
    coreCoolant: "Lead",
    primaryCoolantFlowRate: "-",
    reactorOperatingPressure: "0.1",
    coolantInletTemperature: "400",
    coolantOutletTemperature: "480",
    deltaTemperature: "80",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "-",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "hexahedral",
    numberOfFuelAssemblies: "171",
    fuelMaterial: "MOX",
    claddingMaterial: "-",
    enrichmentOfReloadFuel: "-",
    fuelCycleLength: "-",
    averageDischargeBurnup: "-",
    burnableAbsorber: "-",
    controlRodAbsorber: "-",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "-",
    totalHeightInside: "-",
    transportWeight: "-",
  },
  {
    acronym: "ELECTRA",
    fullName: "European Lead Cooled Training Reactor",
    designOrg: "KTH",
    coolant: "Lead",
    moderator: "No Moderator",
    type: "LFR",
    designStatus: "Under Design",
    country: "Sweden",
    neutronSpectrum: "Fast",
    reactorThermalOutput: "0.5",
    powerPlantGrossOutput: "-",
    powerPlantNetOutput: "-",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "-",
    steamTemperature: "",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "",
    thermodynamicCycle: "-",
    coreCoolant: "Lead",
    primaryCoolantFlowRate: "-",
    reactorOperatingPressure: "-",
    coolantInletTemperature: "400",
    coolantOutletTemperature: "500",
    deltaTemperature: "100",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "-",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "-",
    numberOfFuelAssemblies: "-",
    fuelMaterial: "(Pu,Zr)N",
    claddingMaterial: "-",
    enrichmentOfReloadFuel: "-",
    fuelCycleLength: "360",
    averageDischargeBurnup: "-",
    burnableAbsorber: "-",
    controlRodAbsorber: "-",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "-",
    totalHeightInside: "-",
    transportWeight: "-",
  },
  {
    acronym: "HAPPY200",
    fullName: "Advanced low-Pressurized and Passive SafetY system – 200 MWth",
    designOrg: "SPIC",
    coolant: "-",
    moderator: "H2O",
    type: "PWR",
    designStatus: "Design completed",
    country: "China",
    neutronSpectrum: "-",
    reactorThermalOutput: "200",
    powerPlantGrossOutput: "-",
    powerPlantNetOutput: "-",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "-",
    steamTemperature: "",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "",
    thermodynamicCycle: "-",
    coreCoolant: "-",
    primaryCoolantFlowRate: "1293",
    reactorOperatingPressure: "0.6",
    coolantInletTemperature: "80",
    coolantOutletTemperature: "",
    deltaTemperature: "",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "-",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "Square",
    numberOfFuelAssemblies: "37",
    fuelMaterial: "UO2",
    claddingMaterial: "Zircaloy-4",
    enrichmentOfReloadFuel: "2.76",
    fuelCycleLength: "18",
    averageDischargeBurnup: "40.0",
    burnableAbsorber: "GD203",
    controlRodAbsorber: "-",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "SS316",
    totalHeightInside: "-",
    transportWeight: "-",
  },
  {
    acronym: "MBIR",
    fullName: "Multipurpose fast-neutron research reactor",
    designOrg: "NIKIET",
    coolant: "Sodium",
    moderator: "No moderator",
    type: "PVR",
    designStatus: "Under Design",
    country: "Russia",
    neutronSpectrum: "Fast",
    reactorThermalOutput: "150",
    powerPlantGrossOutput: "60",
    powerPlantNetOutput: "-",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "-",
    steamTemperature: "",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "",
    thermodynamicCycle: "-",
    coreCoolant: "Sodium",
    primaryCoolantFlowRate: "193",
    reactorOperatingPressure: "0.6",
    coolantInletTemperature: "80",
    coolantOutletTemperature: "",
    deltaTemperature: "",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "-",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "Round",
    numberOfFuelAssemblies: "37",
    fuelMaterial: "U2",
    claddingMaterial: "SomeAlloy-4",
    enrichmentOfReloadFuel: "2.76",
    fuelCycleLength: "18",
    averageDischargeBurnup: "5.0",
    burnableAbsorber: "GY203",
    controlRodAbsorber: "-",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "SSE16",
    totalHeightInside: "-",
    transportWeight: "-",
  },
  {
    acronym: "SMART",
    fullName: "System-Integrated Modular Advanced Reactor",
    designOrg: "KAERI",
    coolant: "Light Water",
    moderator: "Light Water",
    type: "PWR",
    designStatus: "Under Design",
    country: "Korea",
    neutronSpectrum: "Fast",
    reactorThermalOutput: "300",
    powerPlantGrossOutput: "40",
    powerPlantNetOutput: "-",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "-",
    steamTemperature: "",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "",
    thermodynamicCycle: "-",
    coreCoolant: "Calcium",
    primaryCoolantFlowRate: "338",
    reactorOperatingPressure: "106",
    coolantInletTemperature: "20",
    coolantOutletTemperature: "",
    deltaTemperature: "",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "-",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "Spherica;",
    numberOfFuelAssemblies: "40",
    fuelMaterial: "TU2",
    claddingMaterial: "SomeAoy-4",
    enrichmentOfReloadFuel: "2.86",
    fuelCycleLength: "78",
    averageDischargeBurnup: "580",
    burnableAbsorber: "YF3",
    controlRodAbsorber: "-",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "HTE16",
    totalHeightInside: "-",
    transportWeight: "-",
  },
  {
    acronym: "TWRP",
    fullName: "Travelling Wave Reactor-Prototype",
    designOrg: "TerraPower",
    coolant: "Sodium",
    moderator: "No Moderator",
    type: "SFR",
    designStatus: "Under Design",
    country: "USA",
    neutronSpectrum: "Fast",
    reactorThermalOutput: "1475",
    powerPlantGrossOutput: "600",
    powerPlantNetOutput: "600",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "23",
    steamTemperature: "100",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "44",
    thermodynamicCycle: "-",
    coreCoolant: "Farhan Nitrate",
    primaryCoolantFlowRate: "338",
    reactorOperatingPressure: "106",
    coolantInletTemperature: "20",
    coolantOutletTemperature: "",
    deltaTemperature: "alpha",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "gamma",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "Beta;",
    numberOfFuelAssemblies: "40",
    fuelMaterial: "TU2",
    claddingMaterial: "SoNyAoy-4",
    enrichmentOfReloadFuel: "66",
    fuelCycleLength: "28",
    averageDischargeBurnup: "50",
    burnableAbsorber: "YRF3",
    controlRodAbsorber: "EE",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "LIB16",
    totalHeightInside: "-",
    transportWeight: "-",
  },
  {
    acronym: "CFBR",
    fullName: "Commenting For Better Reach",
    designOrg: "LINKEDIN",
    coolant: "Comment",
    moderator: "Author",
    type: "COMMENT",
    designStatus: "Under Design",
    country: "India",
    neutronSpectrum: "Slow",
    reactorThermalOutput: "200",
    powerPlantGrossOutput: "30",
    powerPlantNetOutput: "-",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "-",
    steamTemperature: "",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "",
    thermodynamicCycle: "-",
    coreCoolant: "Keyboard",
    primaryCoolantFlowRate: "333",
    reactorOperatingPressure: "667",
    coolantInletTemperature: "880",
    coolantOutletTemperature: "-",
    deltaTemperature: "-",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "-",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "Weird",
    numberOfFuelAssemblies: "40",
    fuelMaterial: "AU",
    claddingMaterial: "DumAloo-4",
    enrichmentOfReloadFuel: "4.66",
    fuelCycleLength: "22",
    averageDischargeBurnup: "60",
    burnableAbsorber: "ABU77",
    controlRodAbsorber: "-",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "OP0216",
    totalHeightInside: "-",
    transportWeight: "400",
  },
  {
    acronym: "W-LFR",
    fullName: "Westinghouse Lead-cooled Fast Reactor",
    designOrg: "WestingHouse Electrical Company",
    coolant: "-",
    moderator: "None",
    type: "LFR",
    designStatus: "Under Design",
    country: "USA",
    neutronSpectrum: "Fast",
    reactorThermalOutput: "500",
    powerPlantGrossOutput: "49",
    powerPlantNetOutput: "-",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "-",
    steamTemperature: "",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "",
    thermodynamicCycle: "-",
    coreCoolant: "Pottasium",
    primaryCoolantFlowRate: "888",
    reactorOperatingPressure: "666",
    coolantInletTemperature: "33",
    coolantOutletTemperature: "",
    deltaTemperature: "",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "-",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "Africa",
    numberOfFuelAssemblies: "40",
    fuelMaterial: "TTF-8",
    claddingMaterial: "LomeAo74",
    enrichmentOfReloadFuel: "2.9",
    fuelCycleLength: "78",
    averageDischargeBurnup: "580",
    burnableAbsorber: "YJJF3",
    controlRodAbsorber: "-",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "HYE16",
    totalHeightInside: "-",
    transportWeight: "-",
  },
  {
    acronym: "VBER-300",
    fullName: "VBER-300",
    designOrg: "OKBM",
    coolant: "LightWater",
    moderator: "No Moderator",
    type: "PWR",
    designStatus: "Under Design",
    country: "RUSSIA",
    neutronSpectrum: "Fast",
    reactorThermalOutput: "175",
    powerPlantGrossOutput: "300",
    powerPlantNetOutput: "200",
    plantEfficiencyNet: "-",
    nonElectricalApplications: "-",
    steamFlowRate: "-",
    steamPressure: "53",
    steamTemperature: "300",
    feedwaterFlowRate: "-",
    feedwaterTemperature: "24",
    thermodynamicCycle: "-",
    coreCoolant: "PreRaju",
    primaryCoolantFlowRate: "445",
    reactorOperatingPressure: "177",
    coolantInletTemperature: "60",
    coolantOutletTemperature: "",
    deltaTemperature: "beta",
    activeCoreHeight: "-",
    equivalentCoreDiameter: "-",
    averageLinearHeatRate: "-",
    averageFuelPowerDensity: "-",
    averageCorePowerDensity: "-",
    outerDiameterFuelRods: "centauri",
    rodArrayOfFuelAssembly: "-",
    latticeGeometry: "crossword;",
    numberOfFuelAssemblies: "40",
    fuelMaterial: "YU2",
    claddingMaterial: "GotyAoy-4",
    enrichmentOfReloadFuel: "96",
    fuelCycleLength: "66",
    averageDischargeBurnup: "90",
    burnableAbsorber: "GGF3",
    controlRodAbsorber: "EE",
    solubleNeutronAbsorber: "-",
    innerDiameterOfCylindricalShell: "-",
    wallThicknessOfCylindricalShell: "-",
    baseMaterial: "BHU77",
    totalHeightInside: "-",
    transportWeight: "-",
  },
];
